# *C-ITS Credential Management System* by https://www.iptelecom.pt[*IP Telecom*]
(* This is work in progress in ALFA development stage...)


## Introduction

The European Commission (EU) runs the C-ITS Point of Contact (CPOC). +
It provides the Trust List Manager (TLM) and a European Certificate Trust Lists (ECTL). +
Further details and related documnentation can de found at https://cpoc.jrc.ec.europa.eu/Documentation.html, including:

* https://cpoc.jrc.ec.europa.eu/data/documents/c-its_security_policy_release_preparatory_phase_of_Delegated_Regulation_2019_1789.pdf[C-ITS Security Policy (EU SP)]
* https://cpoc.jrc.ec.europa.eu/data/documents/c-its_certificate_policy_release_preparatory_phase_of_Delegated_Regulation_2019_1789.pdf[C-ITS Certificate Policy (EU CP)]
* https://cpoc.jrc.ec.europa.eu/data/documents/CPOC_Protocol_Release1.pdf[CPOC Protocol (EU CPOC)]

Active EU CPOC artifacts are publicly available at:

* TLM:  https://cpoc.jrc.ec.europa.eu/L0/gettlmcertificate
* LINK:  https://cpoc.jrc.ec.europa.eu/L0/gettlmlinkcertificate
* ECTL:  https://cpoc.jrc.ec.europa.eu/L0/getectl/1D261F9E338ECB5B

Our C-ITS Credential Management System is based on the current C-ITS security standards: +

* https://www.etsi.org/deliver/etsi_ts/103000_103099/103097/01.03.01_60/ts_103097v010301p.pdf[ETSI TS 103 097 V1.3.1] - Intelligent Transport Systems (ITS) ; Security ; Security  header and certificate formats.
* https://www.etsi.org/deliver/etsi_ts/102900_102999/102941/01.03.01_60/ts_102941v010301p.pdf[ETSI TS 102 941 V1.3.1] - Intelligent Transport Systems (ITS) ; Security ; Trust and Privacy Management.

At the moment our PKI services run a Root Certification Authority (RCA) registered at the EC's https://cpoc.jrc.ec.europa.eu/ECTL.html[ECTL Level 0] trust domain. +

Note that these services are not fully compliant with the C-ITS Security and Certificate Policies requirements, and aim to comply only with the L0 environment guidelines as defined by the European Commission Expert Group on C-ITS Security (E01941), wich are strictly only intended for testing purposes of C-ITS Services.


## Access

The main base URL for the Distribution Center (DC) of our current PKI services is: *https://0.dc.pilot.croads.ccms.pt/*

For reference, and manual or scripted access, current artifacts published by our PKI are directly accessible in native encoding [ASN.1 COER] at:

* Root CA registered at the ECTL Level 0
** RCA:  https://0.dc.pilot.croads.ccms.pt/getcacerts/85987527EE188A49
** RCA-CTL:  https://0.dc.pilot.croads.ccms.pt/getctl/85987527EE188A49
** RCA-CRL:  https://0.dc.pilot.croads.ccms.pt/getcrl/85987527EE188A49

* Pair of CAs geographically restricted to Portugal, typically for provisioning R-ITS-S/RSU, and used for that purpose throughout the C-ROADS Portugal pilot projects: +
** EA-PT:  https://0.ea.pilot.croads.ccms.pt/getcacerts/BA12069B91B8E810
** AA-PT:  https://0.aa.pilot.croads.ccms.pt/getcacerts/9047B112864EDDFD

* Pair of CAs with no geographic restrictions, typically for provisioning V-ITS-S/OBU, and used for that purpose throughout the C-ROADS Portugal pilot projects: +
** EA-WW:  https://0.ea.pilot.croads.ccms.pt/getcacerts/CAC1A29FA18FAF14
** AA-WW:  https://0.aa.pilot.croads.ccms.pt/getcacerts/369F636239546522

* Generic pair of CAs with no restrictions, that can be used for testing or other general purposes: +
** EA-TS:  https://0.ea.pilot.croads.ccms.pt/getcacerts/4C87B1B09B8CD364
** AA-TS:  https://0.aa.pilot.croads.ccms.pt/getcacerts/0646294BB7BE3D8F

All artifacts and service endpoints are discoverable from the ECTL and RCA CTL, as per the ETSI standards. + 

The two main public endpoints for security provisioning of C-ITS stations are:

* https://0.ea.pilot.croads.ccms.pt/ec
* https://0.aa.pilot.croads.ccms.pt/at

The ETSI repository at https://forge.etsi.org/gitlab/ITS/ITS_ASN1 houses related ASN.1 definitions .

The available APIs specifications are accessible and browsable from the root of each service instance:

* RCA/DC:  https://0.dc.pilot.croads.ccms.pt/
* EA:  https://0.ea.pilot.croads.ccms.pt/
* AA:  https://0.aa.pilot.croads.ccms.pt/


## Partner Registration

In order to use our PKI services and provision your equipment for security using our system, you (and/or your company) will need to do initial registration with our service desk. +
At the momment, access to this PKI system is limited to https://www.c-roads.eu/platform.html[C-ROADS Platform] participants/partners that provide correct and verifiable registration information.

If you wish to apply, please send an e-mail to *pki-croads@iptelecom.pt* containing the following information:

* Company Name
* Contact Name
* Contact Email
* HashedID8 of the EAs you wich to use (see list above).
* Maximum number of stations you'll be needing to register, per EA.

We will then provide you with the account credentials that are required to allow you to use the APIs and perform registration of your ITS Stations in our platform. +
After that you are ready to use the service APIs, and may follow more specific instructions in this repository to initialize your equipment's security configuration. 


## Usage

### Station Registration

Standard C-ITS PKI endpoints are not authenticated by definition, but extended APIs always require OpenID Connect based authentication with the account(s) assigned to you. +
You can manage your account at https://auth.undr.ngcs.pt/auth/realms/CCMS.PT/account.

Example: Obtaining an access token and storing it in an environment variable.
[source,bash]
----
export OIDC_ACCESS_TOKEN=$( scripts/oidc-client.sh \
    --token-endpoint https://auth.undr.ngcs.pt/auth/realms/CCMS.PT/protocol/openid-connect/token \
    --operation resource_owner_password_grant \
    --client-id ea.pilot.croads.ccms.pt \
    --scope openid \
    --username <username> \
    --password <password> \
    --field '.access_token') \
&& echo $OIDC_ACCESS_TOKEN
----

The EA API provides authenticated REST endpoints to manage station registration at https://0.ea.pilot.croads.ccms.pt/api/stations. +

The PUT and POST methods accept a JSON structure describing the station(s) to be registered. +

Example: JSON for an hypothetical RSU:
[source,json]
----
{
    "canonical_identifier": "IPTRSU0000000001",
    "public_key": "1bb48707908923c9a6bd5cc9f9c0f46ad51f68223b489ba6f9c0972b85881818",
    "profile": "roadSideUnit",
    "custom_profile": {
        "region": {
            "identifiedRegion ": [ { "countryOnly": 620 } ]
        },
        "appPermissions": [
            { "psid": 36,  "ssp": { "bitmapSsp": "01809c"} },
            { "psid": 37,  "ssp": { "bitmapSsp": "01ffffff"} },
            { "psid": 139,  "ssp": { "bitmapSsp": "01684000fff8"} },            
            { "psid": 141 }
        ]
    }
}
----

The "canonical_identifier", "public_key", and at least one of the "profile" or "custom_profile" fields are mandatory. +

It is recomended that the "canonical_identifier" use a vendor/operator specific prefix. +

The "public_key" is a ASN.1 COER _PublicVerificationKey_ in hexdecimal encoding. +

The "profile" field indicates one of the preset default station profiles as defined by C-ROADS Portugal, and are loosely related to station types. Accepted values are:

* centralStation
* passengerCar
* busOrTram
* specialVehicle
* roadSideUnit

If you omit the "profile" field, then you must provide the "custom_profile" field and vice-versa. +

The "custom_profile" field may fully or partialy define the profile items, so if you provide both fields, the custom definition overrides and/or adds to the preset profile.

Note that in any case the registered profile should comply with the certificate issuance permissions assigned to the correspondent Authorization Auhtority (AA) in order for it to be able to then validate and issue the Authorization Ticket (AT) requests. +


Example: Registering a RSU, using the obtained access token and the above JSON example:

[source,bash]
----
<TBD>
----

You can also use any language or tool that supports OpenAPI 3.0 to access the APIs programaticaly.

Alternativelly you can emails us the information to *pki-croads@iptelecom.pt* indicating:

* Company Name
* Contact Name
* Contact Email
* HashedId8 of the EA to associate the station(s)
* JSON structure for each station to register


## Vendor Specific Information

### Supported Hardware

Some tested hardware systems and software versions are:

* COHDA MK5 release 17.0
* <TBD> ( A-To-B, CTag - comming soon)


